"""remove supervisor_id field (fastapi users model)

Revision ID: 46abdab3f5a4
Revises: 091003eb9438
Create Date: 2025-09-11 19:08:25.060822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46abdab3f5a4'
down_revision: Union[str, Sequence[str], None] = '091003eb9438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_supervisor_id_fkey'), 'user', type_='foreignkey')
    op.drop_column('user', 'supervisor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('supervisor_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('user_supervisor_id_fkey'), 'user', 'user', ['supervisor_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
