"""add unique contraint for teams model

Revision ID: 11f04b4416fe
Revises: 8b3a9dc0ecdc
Create Date: 2025-09-07 20:48:58.701704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11f04b4416fe'
down_revision: Union[str, Sequence[str], None] = '8b3a9dc0ecdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'teams', ['slug'])
    op.create_unique_constraint(None, 'teams', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='unique')
    op.drop_constraint(None, 'teams', type_='unique')
    # ### end Alembic commands ###
