"""add nullable=False to models

Revision ID: 42dc55e0cf65
Revises: 11f04b4416fe
Create Date: 2025-09-08 17:04:04.089222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42dc55e0cf65'
down_revision: Union[str, Sequence[str], None] = '11f04b4416fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'owner_user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.alter_column('teams', 'owner_user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('teams_slug_key'), 'teams', type_='unique')
    op.drop_column('teams', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('slug', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('teams_slug_key'), 'teams', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('teams', 'owner_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.alter_column('companies', 'owner_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
