"""add invite model

Revision ID: a0375455c0d0
Revises: 42dc55e0cf65
Create Date: 2025-09-15 15:13:25.523876

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a0375455c0d0"
down_revision: Union[str, Sequence[str], None] = "42dc55e0cf65"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("teams", sa.Column("company_id", sa.Uuid(), nullable=False))
    op.drop_constraint(op.f("teams_companies_id_fkey"), "teams", type_="foreignkey")
    op.create_foreign_key(
        None, "teams", "companies", ["company_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("teams", "companies_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teams",
        sa.Column("companies_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "teams", type_="foreignkey")
    op.create_foreign_key(
        op.f("teams_companies_id_fkey"),
        "teams",
        "companies",
        ["companies_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("teams", "company_id")
    # ### end Alembic commands ###
