"""current schema is public

Revision ID: c610e1a6c8bf
Revises: 65c041660cd6
Create Date: 2025-08-30 15:52:10.237774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c610e1a6c8bf'
down_revision: Union[str, Sequence[str], None] = '65c041660cd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('memberships_team_id_fkey'), 'memberships', type_='foreignkey')
    op.create_foreign_key(None, 'memberships', 'teams', ['team_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.add_column('teams', sa.Column('owner_user_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('teams_companies_id_fkey'), 'teams', type_='foreignkey')
    op.create_foreign_key(None, 'teams', 'companies', ['companies_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('teams_companies_id_fkey'), 'teams', 'companies', ['companies_id'], ['id'], ondelete='CASCADE')
    op.drop_column('teams', 'owner_user_id')
    op.drop_constraint(None, 'memberships', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('memberships_team_id_fkey'), 'memberships', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
